### ISSUE TITLE
[FRONT] Added URLs to docs buttons

### ISSUE THREAD

**Issue by caioaletroca** [LerianStudio/midaz-console#66]
@eduardadelavle @lerianfezok  Can you verify what URLs should this set of buttons points to?
This screenshot is from the Ledgers Details page.

![Image](https://github.com/user-attachments/assets/9912e3a1-903c-415e-9fd9-d655b108b0e2)

**Comment by eduardadelavle** [comment]
Oi!
GitHub: https://github.com/LerianStudio
Suporte: not yet
CLI docs: not yet
docs: https://docs.lerian.studio
